# This is a basic workflow to help you get started with Actions

name: Test Workflow

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      platform: AWS
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Show Message"
        run: echo "Hello, World!"
      - name: "Show Platform"
        if: ${{ env.platform == 'AWS' }}
        run: |
          echo "Platform: ${{ env.platform }}"
      - name: "Sho default variables"
        run: |
          echo "event: ${{ toJson(github.event) }}"
          echo "event_name: ${{ github.event_name }}"
          echo "event_path: ${{ github.event_path }}"


